# Generated by Django 4.2.6 on 2023-11-01 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarvhit_number', models.CharField(max_length=10, unique=True)),
                ('filling_number', models.CharField(max_length=200)),
                ('filling_date', models.CharField(max_length=25)),
                ('registration_number', models.CharField(max_length=200)),
                ('cnr_number', models.CharField(max_length=20)),
                ('first_hearing', models.CharField(max_length=25)),
                ('case_stage', models.CharField(max_length=100)),
                ('court_no', models.CharField(max_length=100)),
                ('petitioner', models.CharField(max_length=50)),
                ('advocate_name', models.CharField(max_length=100)),
                ('police_station', models.CharField(max_length=250)),
                ('fir_number', models.CharField(max_length=100)),
                ('fir_year', models.CharField(max_length=4)),
                ('fir_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvocateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_agency', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('fh_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('enrollment', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('address1', models.CharField(blank=True, max_length=300, null=True)),
                ('address2', models.CharField(blank=True, max_length=300, null=True)),
                ('address3', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fh_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_act', models.CharField(max_length=200)),
                ('under_section', models.CharField(max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourt.addcase')),
            ],
        ),
        migrations.CreateModel(
            name='RespondentAdvocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('resp_advocate', models.CharField(blank=True, max_length=200, null=True)),
                ('adv_no', models.CharField(blank=True, max_length=10, null=True)),
                ('case_resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourt.addcase')),
            ],
        ),
        migrations.CreateModel(
            name='NextListening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_hearing_date', models.CharField(max_length=25)),
                ('case_stage', models.CharField(max_length=100)),
                ('court_no_judge', models.CharField(max_length=100)),
                ('case_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourt.addcase')),
            ],
        ),
        migrations.CreateModel(
            name='InterimOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details', models.FileField(upload_to='copy_of_orders/')),
                ('next_hearing_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycourt.nextlistening')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_file/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourt.addcase')),
            ],
        ),
        migrations.AddField(
            model_name='addcase',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourt.casetype'),
        ),
        migrations.AddField(
            model_name='addcase',
            name='client_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourt.client'),
        ),
    ]
